import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { Inter } from 'next/font/google'
import AuthProviders from "./context/AuthProvider";


const inter = Inter({
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full dark antialiased ${inter.className}`}
    >
        <body className="min-h-full flex flex-col">
      <AuthProviders>
          {children}
          <Toaster />
      </AuthProviders>
        </body>

    </html>
  );
}
